import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from 'react';
import { useSearchStore } from '../../stores/search.store';
import { useChatStore } from '../../stores/chat.store';
import { Brain, ChevronDown, Trash2, Plus } from 'lucide-react';
export default function Sidebar() {
    const { searchMode, setSearchMode, filters, setFilters } = useSearchStore();
    const { conversationId } = useChatStore();
    const [expandedFilter, setExpandedFilter] = useState('skills');
    const searchModes = [
        { mode: 'vector', label: 'Vector Search', description: 'Semantic matching' },
        { mode: 'keyword', label: 'Keyword Search', description: 'Text search' },
        { mode: 'hybrid', label: 'Hybrid Search', description: 'Combined' },
    ];
    const roles = [
        { id: 'developer', label: 'Developer' },
        { id: 'qa_engineer', label: 'QA Engineer' },
        { id: 'devops_engineer', label: 'DevOps Engineer' },
    ];
    const handleUpdateFilter = (key, value) => {
        setFilters({ ...filters, [key]: value });
    };
    return (_jsxs("aside", { className: "h-full flex flex-col overflow-hidden", children: [_jsx("div", { className: "p-6 border-b border-[#374151]", children: _jsxs("div", { className: "flex items-center gap-3", children: [_jsx("div", { className: "p-2 rounded-lg bg-[#2563EB]", children: _jsx(Brain, { className: "w-6 h-6 text-white" }) }), _jsxs("div", { children: [_jsx("h1", { className: "text-xl font-bold text-[#E5E7EB]", children: "Resume AI" }), _jsx("p", { className: "text-xs text-[#9CA3AF]", children: "Intelligence Platform" })] })] }) }), _jsxs("div", { className: "flex-1 overflow-y-auto", children: [_jsxs("div", { className: "p-6 border-b border-[#374151]", children: [_jsx("h3", { className: "text-sm font-semibold text-[#E5E7EB] mb-3", children: "Your Role" }), _jsx("div", { className: "space-y-2", children: roles.map(({ id, label }) => (_jsx("button", { className: `w-full px-3 py-2 rounded-lg text-sm font-medium transition-colors text-left ${true
                                        ? 'bg-[#2563EB]/10 text-[#2563EB] border border-[#2563EB]'
                                        : 'text-[#9CA3AF] hover:bg-[#374151]'}`, children: label }, id))) }), _jsx("p", { className: "text-xs text-[#6B7280] mt-2", children: "Role affects search recommendations" })] }), _jsxs("div", { className: "p-6 border-b border-[#374151]", children: [_jsx("h3", { className: "text-sm font-semibold text-[#E5E7EB] mb-3", children: "Search Mode" }), _jsx("div", { className: "space-y-2", children: searchModes.map(({ mode, label, description }) => (_jsxs("button", { onClick: () => setSearchMode(mode), className: `w-full px-3 py-2 rounded-lg text-sm font-medium transition-colors text-left ${searchMode === mode
                                        ? 'bg-[#2563EB] text-white'
                                        : 'text-[#9CA3AF] hover:bg-[#1F2937]'}`, children: [_jsx("p", { className: "font-medium", children: label }), _jsx("p", { className: "text-xs opacity-75", children: description })] }, mode))) })] }), _jsxs("div", { className: "p-6 border-b border-[#374151]", children: [_jsx("h3", { className: "text-sm font-semibold text-[#E5E7EB] mb-3", children: "Filters" }), _jsxs("div", { className: "space-y-2", children: [_jsx(FilterItem, { title: "Skills", placeholder: "Python, React, ...", isExpanded: expandedFilter === 'skills', onToggle: () => setExpandedFilter(expandedFilter === 'skills' ? null : 'skills'), value: filters.skills?.join(', ') || '', onChange: (val) => handleUpdateFilter('skills', val ? val.split(',').map((s) => s.trim()) : []) }), _jsx(FilterItem, { title: "Experience", placeholder: "5+ years", isExpanded: expandedFilter === 'experience', onToggle: () => setExpandedFilter(expandedFilter === 'experience' ? null : 'experience'), value: filters.experience || '', onChange: (val) => handleUpdateFilter('experience', val) }), _jsx(FilterItem, { title: "Location", placeholder: "San Francisco, NYC...", isExpanded: expandedFilter === 'location', onToggle: () => setExpandedFilter(expandedFilter === 'location' ? null : 'location'), value: filters.location || '', onChange: (val) => handleUpdateFilter('location', val) }), _jsx(FilterItem, { title: "Company", placeholder: "Google, Meta...", isExpanded: expandedFilter === 'company', onToggle: () => setExpandedFilter(expandedFilter === 'company' ? null : 'company'), value: filters.currentCompany || '', onChange: (val) => handleUpdateFilter('currentCompany', val) })] })] }), _jsxs("div", { className: "p-6", children: [_jsxs("div", { className: "flex items-center justify-between mb-3", children: [_jsx("h3", { className: "text-sm font-semibold text-[#E5E7EB]", children: "History" }), _jsx("button", { className: "p-1 rounded hover:bg-[#374151] transition-colors", children: _jsx(Plus, { className: "w-4 h-4 text-[#9CA3AF]" }) })] }), _jsxs("div", { className: "space-y-2 max-h-64 overflow-y-auto", children: [_jsx(ConversationItem, { title: "Python ML Engineers", timestamp: "2 hours ago", isActive: conversationId === 'conv_1' }), _jsx(ConversationItem, { title: "React Developers", timestamp: "1 day ago", isActive: conversationId === 'conv_2' }), _jsx(ConversationItem, { title: "DevOps with K8s", timestamp: "3 days ago", isActive: conversationId === 'conv_3' })] }), _jsx("p", { className: "text-xs text-[#6B7280] mt-3", children: "No active conversations yet" })] })] })] }));
}
function FilterItem({ title, placeholder, isExpanded, onToggle, value, onChange, }) {
    return (_jsxs("div", { children: [_jsxs("button", { onClick: onToggle, className: "w-full flex items-center justify-between px-3 py-2 rounded-lg hover:bg-[#374151] transition-colors group", children: [_jsx("label", { className: "text-xs font-medium text-[#9CA3AF] cursor-pointer", children: title }), _jsx(ChevronDown, { className: `w-4 h-4 text-[#6B7280] transition-transform ${isExpanded ? 'rotate-180' : ''}` })] }), isExpanded && (_jsx("div", { className: "px-3 py-2", children: _jsx("input", { type: "text", placeholder: placeholder, value: value, onChange: (e) => onChange(e.target.value), className: "w-full px-3 py-2 rounded-lg bg-[#1F2937] border border-[#374151] text-[#E5E7EB] text-sm placeholder-[#6B7280] focus:outline-none focus:border-[#2563EB] transition-colors" }) }))] }));
}
function ConversationItem({ title, timestamp, isActive, }) {
    return (_jsx("div", { className: `p-3 rounded-lg cursor-pointer transition-all group ${isActive
            ? 'bg-[#2563EB]/20 border border-[#2563EB]'
            : 'bg-[#1F2937] hover:bg-[#374151] border border-transparent'}`, children: _jsxs("div", { className: "flex items-start justify-between gap-2", children: [_jsxs("div", { className: "flex-1 min-w-0", children: [_jsx("p", { className: `text-sm font-medium truncate ${isActive ? 'text-[#2563EB]' : 'text-[#E5E7EB]'}`, children: title }), _jsx("p", { className: "text-xs text-[#6B7280] mt-1", children: timestamp })] }), _jsx("button", { className: "p-1 rounded opacity-0 group-hover:opacity-100 transition-opacity hover:bg-[#EF4444]/20", title: "Delete conversation", children: _jsx(Trash2, { className: "w-3 h-3 text-[#EF4444]" }) })] }) }));
}
//# sourceMappingURL=Sidebar.js.map